version: '0.2'
words:
  - DECI
  - CENTI
  - MILLI
  - MILLIWATT
  - Benoit
  - catppuccin
  - chargingstations
  - ctrlr
  - csms
  - idtag
  - idtags
  - iccid
  - imsi
  - ocpp
  - onconnection
  - opencode
  - evse
  - evses
  - kvar
  - kvarh
  - varh
  - rfid
  - workerset
  - worktree
  - dedup
  - unpushed
  - logform
  - mnemonist
  - poolifier
  - measurand
  - measurands
  - mikro
  - neostandard
  - recurrency
  - shutdowning
  - VCAP
  - workerd
  - yxxx
  - cppwm
  - heartbeatinterval
  - HEARTBEATINTERVAL
  - websocketpinginterval
  - WEBSOCKETPINGINTERVAL
  - connectionurl
  - CONNECTIONURL
  - chargingstation
  - CHARGINGSTATION
  - authctrlr
  - AUTHCTRLR
  - recloser
  - deauthorize
  - Deauth
  - DEAUTHORIZE
  - deauthorized
  - DEAUTHORIZED
  - Deauthorization
  - Selftest
  - SECC
  - Secc
  - Overcurrent
  - ocsp
  - OCSP
  - EMAID
  - emaid
  - IDTOKEN
  - idtoken
  - issuerkeyhash
  - issuernamehash
  - SRPC
  - CALLRESULT
  - CALLERROR
  - CALLRESULTERROR
  - reservability
  - PPTP
  - UIMCP
  - Streamable
  - modelcontextprotocol
  - OCMF
  - ocmf
  - secp
  - brainpool
  - Eichrecht
  - eichrecht
  - signingmethod
  - SIGNINGMETHOD
  - encodingmethod
  - ENCODINGMETHOD
  - signedmeterdata
  - SIGNEDMETERDATA
  - fiscalmetering
  - FISCALMETERING
  - publickeywithsignedmetervalue
  - PUBLICKEYWITHSIGNEDMETERVALUE
  - sampleddatasignreadings
  - SAMPLEDDATASIGNREADINGS
  - focusables
  - Focusables
  - secret
