packages:
  - ./
  - ./ui/web

overrides:
  d3-color@<3.1.0: '>=3.1.0'
  form-data@<2.5.4: '>=2.5.4'
  got@<11.8.5: '>=11.8.5'
  qs@<6.14.1: '>=6.14.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  uuid@<7: '>=7.0.0'
