packages:
  - ./
  - ./ui/common
  - ./ui/cli
  - ./ui/web

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: false
  bufferutil: false
  es5-ext: false
  esbuild: false
  msgpackr-extract: false
  utf-8-validate: false

patchedDependencies:
  '@ai-hero/sandcastle@0.5.11': patches/@ai-hero__sandcastle@0.5.11.patch
