packages:
  - ./
  - ./ui/common
  - ./ui/cli
  - ./ui/web

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: false
  bufferutil: false
  es5-ext: false
  esbuild: false
  msgpackr-extract: false
  utf-8-validate: false

minimumReleaseAgeExclude:
  - ip-address@10.1.1

overrides:
  ip-address@<=10.1.0: ^10.1.1

patchedDependencies:
  '@ai-hero/sandcastle': patches/@ai-hero__sandcastle.patch
