packages:
  - ./
  - ./ui/web
overrides:
  'cacheable-request': '^10.2.10'
  'd3-color': '^3.1.0'
  'ejs': '^3.1.9'
  'got': '^12.6.1'
  'nanoid': '^3.3.8'
  'semver': '^7.5.3'
  'tough-cookie': '^4.1.3'
  'uuid': '^9.0.0'
