// flow-typed signature: 7ce143f62e46f69c1f0d226420c51772
// flow-typed version: <<STUB>>/clinic_v^7.0.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clinic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clinic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clinic/bin' {
  declare module.exports: any;
}

declare module 'clinic/lib/authenticate' {
  declare module.exports: any;
}

declare module 'clinic/lib/clean' {
  declare module.exports: any;
}

declare module 'clinic/lib/get-ask-message' {
  declare module.exports: any;
}

declare module 'clinic/lib/help-formatter' {
  declare module.exports: any;
}

declare module 'clinic/lib/tar-and-upload' {
  declare module.exports: any;
}

declare module 'clinic/test-local/cli-doctor-collect-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test-local/cli-flame-collect-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test-local/cli-flame-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test-local/cli-flame-passthrough-flags' {
  declare module.exports: any;
}

declare module 'clinic/test-local/cli-flame-visualize-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/authenticate.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-ask-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-ask-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-ask-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-autocannon.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-collect-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-non-node.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-version.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-bubbleprof-visualize-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-clean-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-clean-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-clinic-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-clinic-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-clinic-version.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-collect-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-non-node.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-version.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-doctor-visualize-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-full.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-non-node.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-upload.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-version.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-flame-visualize-only.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-login-logout.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-upload-files.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-upload-help.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli-upload-no-args.test' {
  declare module.exports: any;
}

declare module 'clinic/test/cli' {
  declare module.exports: any;
}

declare module 'clinic/test/fake-upload-server' {
  declare module.exports: any;
}

declare module 'clinic/test/help-formatter.test' {
  declare module.exports: any;
}

declare module 'clinic/test/server' {
  declare module.exports: any;
}

declare module 'clinic/test/tar-and-upload.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clinic/bin.js' {
  declare module.exports: $Exports<'clinic/bin'>;
}
declare module 'clinic/lib/authenticate.js' {
  declare module.exports: $Exports<'clinic/lib/authenticate'>;
}
declare module 'clinic/lib/clean.js' {
  declare module.exports: $Exports<'clinic/lib/clean'>;
}
declare module 'clinic/lib/get-ask-message.js' {
  declare module.exports: $Exports<'clinic/lib/get-ask-message'>;
}
declare module 'clinic/lib/help-formatter.js' {
  declare module.exports: $Exports<'clinic/lib/help-formatter'>;
}
declare module 'clinic/lib/tar-and-upload.js' {
  declare module.exports: $Exports<'clinic/lib/tar-and-upload'>;
}
declare module 'clinic/test-local/cli-doctor-collect-only.test.js' {
  declare module.exports: $Exports<'clinic/test-local/cli-doctor-collect-only.test'>;
}
declare module 'clinic/test-local/cli-flame-collect-only.test.js' {
  declare module.exports: $Exports<'clinic/test-local/cli-flame-collect-only.test'>;
}
declare module 'clinic/test-local/cli-flame-full.test.js' {
  declare module.exports: $Exports<'clinic/test-local/cli-flame-full.test'>;
}
declare module 'clinic/test-local/cli-flame-passthrough-flags.js' {
  declare module.exports: $Exports<'clinic/test-local/cli-flame-passthrough-flags'>;
}
declare module 'clinic/test-local/cli-flame-visualize-only.test.js' {
  declare module.exports: $Exports<'clinic/test-local/cli-flame-visualize-only.test'>;
}
declare module 'clinic/test/authenticate.test.js' {
  declare module.exports: $Exports<'clinic/test/authenticate.test'>;
}
declare module 'clinic/test/cli-ask-full.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-ask-full.test'>;
}
declare module 'clinic/test/cli-ask-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-ask-help.test'>;
}
declare module 'clinic/test/cli-ask-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-ask-no-args.test'>;
}
declare module 'clinic/test/cli-autocannon.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-autocannon.test'>;
}
declare module 'clinic/test/cli-bubbleprof-collect-only.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-collect-only.test'>;
}
declare module 'clinic/test/cli-bubbleprof-full.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-full.test'>;
}
declare module 'clinic/test/cli-bubbleprof-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-help.test'>;
}
declare module 'clinic/test/cli-bubbleprof-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-no-args.test'>;
}
declare module 'clinic/test/cli-bubbleprof-non-node.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-non-node.test'>;
}
declare module 'clinic/test/cli-bubbleprof-version.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-version.test'>;
}
declare module 'clinic/test/cli-bubbleprof-visualize-only.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-bubbleprof-visualize-only.test'>;
}
declare module 'clinic/test/cli-clean-full.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-clean-full.test'>;
}
declare module 'clinic/test/cli-clean-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-clean-help.test'>;
}
declare module 'clinic/test/cli-clinic-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-clinic-help.test'>;
}
declare module 'clinic/test/cli-clinic-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-clinic-no-args.test'>;
}
declare module 'clinic/test/cli-clinic-version.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-clinic-version.test'>;
}
declare module 'clinic/test/cli-doctor-collect-only.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-collect-only.test'>;
}
declare module 'clinic/test/cli-doctor-full.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-full.test'>;
}
declare module 'clinic/test/cli-doctor-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-help.test'>;
}
declare module 'clinic/test/cli-doctor-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-no-args.test'>;
}
declare module 'clinic/test/cli-doctor-non-node.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-non-node.test'>;
}
declare module 'clinic/test/cli-doctor-version.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-version.test'>;
}
declare module 'clinic/test/cli-doctor-visualize-only.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-doctor-visualize-only.test'>;
}
declare module 'clinic/test/cli-flame-full.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-full.test'>;
}
declare module 'clinic/test/cli-flame-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-help.test'>;
}
declare module 'clinic/test/cli-flame-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-no-args.test'>;
}
declare module 'clinic/test/cli-flame-non-node.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-non-node.test'>;
}
declare module 'clinic/test/cli-flame-upload.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-upload.test'>;
}
declare module 'clinic/test/cli-flame-version.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-version.test'>;
}
declare module 'clinic/test/cli-flame-visualize-only.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-flame-visualize-only.test'>;
}
declare module 'clinic/test/cli-login-logout.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-login-logout.test'>;
}
declare module 'clinic/test/cli-upload-files.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-upload-files.test'>;
}
declare module 'clinic/test/cli-upload-help.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-upload-help.test'>;
}
declare module 'clinic/test/cli-upload-no-args.test.js' {
  declare module.exports: $Exports<'clinic/test/cli-upload-no-args.test'>;
}
declare module 'clinic/test/cli.js' {
  declare module.exports: $Exports<'clinic/test/cli'>;
}
declare module 'clinic/test/fake-upload-server.js' {
  declare module.exports: $Exports<'clinic/test/fake-upload-server'>;
}
declare module 'clinic/test/help-formatter.test.js' {
  declare module.exports: $Exports<'clinic/test/help-formatter.test'>;
}
declare module 'clinic/test/server.js' {
  declare module.exports: $Exports<'clinic/test/server'>;
}
declare module 'clinic/test/tar-and-upload.test.js' {
  declare module.exports: $Exports<'clinic/test/tar-and-upload.test'>;
}
