// flow-typed signature: 8db3d2774e19ee3032aed9ad3984b679
// flow-typed version: <<STUB>>/eslint-config-node_v^4.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-node' {
  declare module.exports: any;
}
