// flow-typed signature: 67fce3444f2d1a1266770c7fb04c58f9
// flow-typed version: <<STUB>>/eslint-config-esnext_v^4.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-esnext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-esnext' {
  declare module.exports: any;
}
