// flow-typed signature: 266abab1324d9dc432f9945dfa50e622
// flow-typed version: <<STUB>>/eslint-config-node_v^4.1.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-node' {
  declare module.exports: any;
}
