// flow-typed signature: 969a8eb17cd2cb030f883aa82330d221
// flow-typed version: <<STUB>>/worker-threads-pool_v^2.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-threads-pool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-threads-pool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'worker-threads-pool/index' {
  declare module.exports: $Exports<'worker-threads-pool'>;
}
declare module 'worker-threads-pool/index.js' {
  declare module.exports: $Exports<'worker-threads-pool'>;
}
