name: 'Bug report'
title: '[BUG]'
description: Create a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found in charging-stations-simulator.

        Please fill in as much of the template below as you're able.
  - type: checkboxes
    attributes:
      options:
        - label:
            I've searched for any related issues and avoided creating a
            duplicate issue.
          required: true
  - type: textarea
    attributes:
      label: Description
      description:
        Description of the bug.
  - type: input
    attributes:
      label: charging-stations-simulator version
  - type: input
    attributes:
      label: Node.js Version
      description: Output of `node -v`.
  - type: textarea
    attributes:
      label: System
      description: Output of `npx envinfo --system`.
  - type: textarea
    attributes:
      label: Expected result
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Actual result
      description: What actually happened.
  - type: textarea
    attributes:
      label: Attachments
      description: Logs, screenshots, screencast, etc.
