import { OCPP16ChargePointStatus } from '../../../types';
import { OCPPConstants } from '../internal';

export class OCPP16Constants extends OCPPConstants {
  static readonly OCPP16ChargePointStatusChargingStationTransition = new Set<
    [OCPP16ChargePointStatus | undefined, OCPP16ChargePointStatus | undefined]
  >([
    [undefined, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Faulted],
    [undefined, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Faulted],
    [undefined, OCPP16ChargePointStatus.Faulted],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Unavailable],
    // [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Faulted],
  ]);

  static readonly OCPP16ChargePointStatusConnectorTransition = new Set<
    [OCPP16ChargePointStatus | undefined, OCPP16ChargePointStatus | undefined]
  >([
    [undefined, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.SuspendedEVSE],
    // [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Finishing],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Available, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Reserved],
    // [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Preparing, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Preparing],
    // [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Charging, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Charging],
    // [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.SuspendedEV, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Available],
    // [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.SuspendedEV],
    // [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.SuspendedEVSE, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.Finishing],
    [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Preparing],
    // [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Charging],
    // [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.SuspendedEV],
    // [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.SuspendedEVSE],
    // [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Finishing, OCPP16ChargePointStatus.Faulted],
    // [undefined, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Preparing],
    // [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Charging],
    // [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.SuspendedEV],
    // [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.SuspendedEVSE],
    // [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Reserved, OCPP16ChargePointStatus.Faulted],
    [undefined, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.SuspendedEVSE],
    // [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Finishing],
    // [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Reserved],
    // [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Unavailable],
    [OCPP16ChargePointStatus.Unavailable, OCPP16ChargePointStatus.Faulted],
    [undefined, OCPP16ChargePointStatus.Faulted],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Available],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Preparing],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Charging],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.SuspendedEV],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.SuspendedEVSE],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Finishing],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Reserved],
    [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Unavailable],
    // [OCPP16ChargePointStatus.Faulted, OCPP16ChargePointStatus.Faulted],
  ]);
}
