sonar.projectKey=e-mobility-charging-stations-simulator-web
sonar.organization=sap-1
sonar.projectName=e-mobility-charging-stations-simulator-web
# x-release-please-start-version
sonar.projectVersion=4.6.0
# x-release-please-end
sonar.sources=src
sonar.tests=tests

sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
